co2 layout setup
HZ-HBOICT-Y2-2425/uvc-project-frontend-greenshift-11 pull request #5
Opened 2024-11-27 10:58 UTC by zmyslek

2024-11-27 11:02 UTC, JoeriH06 requested changes
look at the comments

2024-11-27 11:02 UTC, JoeriH06 commented on src/routes/co2/+page.svelte
Make the script --> eithr without the comments, or explain what the comments mean
Then we use tailwind, there should not be any <style> make it mobile first as always with the classes that are given in the tailwind docs

2024-11-27 11:02 UTC, JoeriH06 commented on src/routes/+layout.svelte
Why from auto to 0???

2024-11-27 11:02 UTC, JoeriH06 commented on package.json
why is this extra dependencie added? i dont think we need it, because we use tailwind as our "canvas"

2024-11-28 16:28 UTC, zmyslek commented on src/routes/+layout.svelte
cause 0 is needed and auto does not ensure that

2024-11-28 16:28 UTC, zmyslek commented on src/routes/co2/+page.svelte
done

2024-11-28 16:47 UTC, closed without merging